# Dependencies
markdown:         kramdown

exclude:  ['/bower_components','/node_modules','/test','bower.json','CNAME','Gruntfile.js','LICENSE','package.json','README.md']

# Permalinks
permalink:        /posts/:year/:month/:day/:title/

# Server
host:             0.0.0.0
port:             9001
url:              http://www.unclezheng.com
encoding:         UTF-8

paginate_path : "blog/page:num/"
paginate : 5

# Custom vars
author: 
  name: "Uncle Zheng"
  github: "https://github.com/zhengyongbo"
  facebook: "https://www.facebook.com/unclezheng"
  linkedin: "https://www.linkedin.com/in/unclezheng"
  email: "zhengyongbo0128@gmail.com"
  address: "Zhuzhou City, Hunan Province, China"
  phone: "18579060990"
  qq: "158285920"

